version: "3.9"

services:
  personal-page-stats:
    image: ghcr.io/aaronwork1205/personal-page-stats:latest
    ports:
      - "8090:8090"
    volumes:
      - ./personal-page-stats:/app/data
    restart: unless-stopped
